Calc
vialikanau-aliaksei/vialikanau-aliaksei.github.io pull request #1
Opened 2017-03-20 17:51 UTC by vialikanau-aliaksei

2017-03-21 05:21 UTC, NikitaSedyx requested changes

2017-03-21 05:21 UTC, NikitaSedyx commented on js/calc.js
> +      result = Math.round(a / b);
`Math.round(6.9 / 1) == 7` but it should be 6

2017-03-21 05:29 UTC, vialikanau-aliaksei commented on js/calc.js
> +      result = Math.round(a / b);
why 6?  Change rounding to (a/b)^0 ?

2017-03-21 19:17 UTC, NikitaSedyx requested changes

2017-03-21 19:17 UTC, NikitaSedyx commented on index.html
> +<form name="main">
please move each task to new folder, thank

2017-03-21 19:17 UTC, NikitaSedyx commented on index.html
> +<form name="main">
also please add spaces for nested tags

2017-03-21 19:17 UTC, NikitaSedyx commented on js/calc.js
> +      result = (a / b) ^ 0;
1/0 ^ 0 = 0
but I want to be Infinity
please look at Math function

2017-03-23 18:07 UTC, NikitaSedyx approved these changes

2017-03-25 12:12 UTC, merged