array
vialikanau-aliaksei/vialikanau-aliaksei.github.io pull request #3
Opened 2017-03-25 17:08 UTC by vialikanau-aliaksei

2017-03-25 20:02 UTC, NikitaSedyx requested changes

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +  return Array.isArray(object);
it's cool you know Array method and can use it, but I want to see your implementation

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +  return Array.isArray(object);
have seen below, please remove this function, it doesn't make sense

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +  if (end == undefined) {
it's better to check ===
null == undefined = true

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +function range(start, end, step) {
please look at requirements for function range(5) should return [0, 1, 2, 3, 4]
(1, 5) ->  [1, 2, 3, 4]

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +    return element != false;
could you read what values are falsy? and how to use them in conditions

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +  var set = {};
basically set is array in js

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +    var isExist = set[element];
it won't work with objects
remember what type has index: String. when you do `set[element]`, toString() is called on element

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +      array.splice(i, 1);
you mutate array here, it's not cool

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +    --array.length;
again, you mutates array

2017-03-25 20:02 UTC, NikitaSedyx commented on array/js/array.js
> +function excludeLast2(array, count) {
same in this func

2017-03-26 06:03 UTC, vialikanau-aliaksei commented on array/js/array.js
> +    return element != false;
compact([1, 0, 3, false, 5, NaN, null, undefined, '']) is passed to [1, 3, 5]

2017-03-26 11:17 UTC, NikitaSedyx requested changes

2017-03-26 11:17 UTC, NikitaSedyx commented on array/js/array.js
> +function excludeLast2(array, count) {
negative count increases array length, could you make changes if count <= 0 to return new array without any changes

2017-03-26 11:17 UTC, NikitaSedyx commented on array/js/array.js
> +  return array.slice(0, array.length - count);
same

2017-03-26 11:17 UTC, NikitaSedyx commented on array/js/array.js
> +    return element ? true : false;
`return element` will work... please read why

2017-03-26 18:28 UTC, NikitaSedyx approved these changes

2017-03-27 18:42 UTC, NikitaSedyx requested changes

2017-03-27 18:42 UTC, NikitaSedyx commented on array/js/array.js
> +  return {}.toString.call(object) == "[object Array]";
are you sure it works?
`SyntaxError: expected expression, got '.' `is in my console

2017-03-27 21:49 UTC, vialikanau-aliaksei commented on array/js/array.js
> +  return {}.toString.call(object) == "[object Array]";
yep, working in edge and chrome 57. I'll to do bug fix for console

2017-03-28 06:08 UTC, NikitaSedyx approved these changes

2017-04-27 12:48 UTC, merged